name: Deploy to Firebase Function on PR
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions
        env:
          #call firebase login:ci to generate token for Gihub Secret in your PC
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: projectId